### ISSUE TITLE
Providing a namespace breaks the CF config function in script

### ISSUE THREAD

**Issue by widapro** [codefresh-support/cf-on-premises-support#1]
If, according to the instructions in the README, you specify the namespace, this will lead to the following error:
```
% ./cf-onprem-support-package.sh codefresh
Creating Codefresh On-Premises Temp Directory
Gathering Codefresh On-Premises Information:
cat: codefresh: No such file or directory
cat: codefresh: No such file or directory
cat: codefresh: No such file or directory
 - Using Codefresh URL null
   ↳ Token of null
 - Getting Codefresh On-Premises Accounts
 - Getting Codefresh On-Premises Runtimes
 - Release Version
 ```
It happens because in line [#9](https://github.com/codefresh-support/cf-on-premises-support/blob/main/cf-onprem-support-package.sh#L9) and [#21](https://github.com/codefresh-support/cf-on-premises-support/blob/main/cf-onprem-support-package.sh#L21) uses the same first argument from command line.

```
NAMESPACE="${1:-codefresh}"
```
```
CFCONFIG=${1:-~/.cfconfig}
```

**Comment by alexaladov-codefresh** [comment]
Thank you for reporting this issue @widapro , we're working on a fix!
